### ISSUE TITLE
Timed out waiting for container port to open

### ISSUE THREAD

**Issue by memekas** [testcontainers/testcontainers-java#4602]
https://github.com/testcontainers/testcontainers-java/issues/4125 is still reproducible. I can't downgrade my docker because of apple m1 chip. Earlier versions do not support it.

```
import org.testcontainers.containers.GenericContainer
import org.testcontainers.utility.DockerImageName

open class KGenericContainer(image: String) : GenericContainer<KGenericContainer>(DockerImageName.parse(image))

fun main() {
    val container = KGenericContainer("MY_CONTAINER")
        .withExposedPorts(8081)
    container.start()
}
```

```
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [62362] should be listening)
	at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:49)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:923)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:466)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:329)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:327)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:315)
```
macbook m1 chip
macOS 11.6
docker desktop 4.1.1
docker engine 20.10.8
testcontainers 1.16.0
Kotlin 1.5
JVM 11

**Comment by DJ-Glock** [comment]
Hi all
I had a similar issue and it looks like I've found the cause once I read this document: https://www.testcontainers.org/features/startup_and_waits/

In my case issue happened because I set `.withExposedPorts(80)`, but container was not going to listen this port. And it gave me similar error with random port. Once I removed `.withExposedPorts(80)`, container was able to start.


@memekas are you sure if port 8081 is correct for your container and it should listen to it?
```
fun main() {
    val container = KGenericContainer("MY_CONTAINER")
        .withExposedPorts(8081)
    container.start()
}
```

**Comment by memekas** [comment]
It looks like my problem is that the program inside the container takes a long time to start, so the check for ports availability does not pass.

I found that it is possible to increase the startup timeout. Is it possible to disable the port openness check? Docker writes that the ports are forwarded, and this is the main thing for me. And whether there is a program on them or not is a different case.

**Comment by kiview** [comment]
I struggle to understand your Testcontainers usage patterns in this case. However, you can configure Testcontainers' wait strategies according to your needs:
https://www.testcontainers.org/features/startup_and_waits/

**Comment by memekas** [comment]
Yeah. I understood. There are no standard strategies that I need. I have implemented my own strategy. The question is, is it possible to disable checks? I don’t know why to do this. Maybe for quick testing it might be helpful... But yes it sounds useless

**Comment by hemant-hpe** [comment]
With 1.17.1 still getting the same error : `2023-11-27 15:45:40.239 PST [main] [ERROR] 🐳 [amazon/dynamodb-local:latest] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [57847] should be listening)
	at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:90)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:51)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:929)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:468)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)
`
