### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by bearrito** [testcontainers/testcontainers-java#478]
I am seeing the following issue while running inside a container via our Jenkinsfile

Our Jenkinsfiles looks something like
```
      stage 'Entering Build Container'
      docker.image('repo.jfrog.io/jenkins-docker').inside() {
        sshagent(['jenkins_github']){
          stage 'Run Test'
          sh ' gradle test'
}
```

```
mytestIT > classMethod FAILED
    java.lang.ExceptionInInitializerError
        Caused by: java.lang.IllegalStateException at mytestIT.java:53

37 tests completed, 1 failed
:test FAILED
```

At that line in my test I have the following

```
@ClassRule
    public static GenericContainer es =

            new GenericContainer("elk:latest")
                    .withExposedPorts(9200,5601,9300,5044)
                    .waitingFor(Wait.forListeningPort());
```

This test runs fine locally.

**Comment by bearrito** [comment]
I read that and saw the section that mentions
`TestContainers will automatically detect if it's inside a container and instead of "localhost" will use the default gateway's IP.` I don't believe we use volume mapping?

Maybe someone in the community has an example of using these with Jenkinsfile.

**Comment by bsideup** [comment]
@bearrito it's not about the volume mapping.

**Comment by bearrito** [comment]
The documentation states that TestContainers will automatically detect if runing in a container and do the right thing. Then it goes onto state

```
However, additional configuration is required if you use volume mapping. The following points need to be considered:```

However, I'm not using volume mapping, so I my case it seems there is no further configuration to perform?

Disregarding volume mapping, what are the further configuration steps. None are apparent in the docs.

**Comment by bsideup** [comment]
@bearrito good point, we should fix the docs. `-v /var/run/docker.sock:/var/run/docker.sock` is mandatory when you run TestContainers inside a container.

**Comment by bearrito** [comment]
noted.

**Comment by bearrito** [comment]
For future Jenkinsfile users what worked for me was very simple
```
 docker.image('container.jfrog.io/jenkins-docker').inside('-u root -v /var/run/docker.sock:/var/run/docker.sock') 
```

However the test container didn't seem to resolve the correct ip (or perhaps something is odd about or docker networking)

I ended up working around with something like the below snippet

```
apiPort = 9300;
exposedPort = es.getMappedPort(apiPort);
String ipAddress = es.getContainerIpAddress();
boolean runningInDocker = (System.getenv("IN_JENKINS_DOCKER_BUILD") !=null);
 if(runningInDocker){
      exposedPort = apiPort;
      ipAddress = es.getContainerInfo().getNetworkSettings().getIpAddress();
        }
```

I think this issue can be closed.
