### ISSUE TITLE
[Bug] Reuse hash changes any time my docker registry token is renewed

### ISSUE THREAD

**Issue by Dayde** [testcontainers/testcontainers-java#5290]
Hi,

I have this really weird behaviour where testcontainers are reused but not always. If the container was just started, running my test again never starts a new one, but after a moment, about 5 minutes, it always creates a new one.

A little debugging session led me to the `hash` method in `GenericContainer` class.

It appears the `createCommand` used to generate that hash, contains docker auth elements.
Under the key `authConfig`, I think the key `password` contains the docker registry token because the username is `_dcgcloud_token` (using a google artifact registry as a docker registry). 
The token being renewed automatically every now and then it breaks the container reusability.

As I see it we could simply remove this key from the command just before generating the hash, would that make sense to you ?

**Comment by bsideup** [comment]
Hi @Dayde,

What version of Testcontainers are you using?

**Comment by bsideup** [comment]
This was fixed in docker-java 3.2.13 and the latest Testcontainers uses it:
https://github.com/docker-java/docker-java/pull/1807

https://github.com/testcontainers/testcontainers-java/blob/46ba812ab2315626ca3d90c7432a2a0bbb544f5e/core/build.gradle#L79

**Comment by Dayde** [comment]
You’re perfectly right I bumped the version to 1.17.1 before reporting this but I must have skipped a necessary maven clean/reload in IJ as I was still seeing the issue then.
I reran a bunch of test today and it’s working like a charm.

Sorry for this waste of your time and many thanks for the fix 😄
